- config.sample/dkim/dkim_key_gen.sh
Fix a typo in config.sample/dkim/dkim_key_gen.sh.
(I've been working on the Drupal open source project for over 7 years, but Drupal is not on GitHub, So, this nit is my first active use of GitHub. Please bear with me and let me know if I'm doing something wrong.)
> Fix a stray quote in the generated 'dns' file.

- lib/Qpsmtpd/SMTP.pm
If a client is using SSL, then Spamassassin won't be able to detect user authentication. This change will fix the problem.
Relevant code in Spamassassin source:
if (/ by / && / with ((?:ES|L|UTF8S|UTF8L)MTPS?A|ASMTP|HTTPU?)(?: |;|$)/i) {
Basically if we insert comment between 'with' and 'ESMTPSA', then Spamassassin won't be able to tell if the session is authenticated.
Old Debian bug for reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684571
> Change Received header ordering when using SSL, to fix interaction problem with Spamassassin

- plugins/ident/geoip
- t/plugin_tests/ident/geoip
Previously, the GeoIP plugin would crash on certain missing GeoIP data.
Now it will continue to operate on whatever data it can get at.
Note that it already warns when any data it's looking for is missing.
> Handle missing GeoIP data gracefully

- plugins/greylisting
prune_db() and migrate_db() already call unlock(), calling
cleanup_and_return() only added a second (redundant) call to unlock()
> Remove unnecessary calls to cleanup_and_return()

- plugins/greylisting
- t/plugin_tests/greylisting
Previously the greylist plugin tried to use redis and fell back to DBM.  This means that if a system already had an established DBM database, but happened to have Redis running, the existing DBM db would be abandoned for a new Redis DB.  This would inevitably lead to more delays for legitimate mail, and possibly lost mail.
This adds a 'redis' argument which enables Redis and sets the location of the redis server; if it is not explicitly set, DBM is used instead.
If the redis server is unavailable, rather than failing to start QP, we instead fail to register the plugin.
> Make Redis optional

- lib/Qpsmtpd/DB/File/DBM.pm
- lib/Qpsmtpd/DB/Redis.pm
- plugins/greylisting
- t/plugin_tests/greylisting
- t/qpsmtpd-db-file-dbm.t
- t/qpsmtpd-db-redis.t
Reduce round trips to Redis by taking advantage of mget() and passing all deleted keys to del() at once, speeding up expiration of the greylist database significantly.
Across a WAN (admittedly the worst case scenario), prune_db() previously took 6 minutes, 56 seconds to check 11,374 DB entries for expiration.  Now it takes 3 seconds.  Hooray!
> Speed up greylisting prune_db() for Redis

- .perltidyrc
Revert to default of -pt=1 rather than -pt=2:
> -bt,-pt,-sbt: Container tightness
> These are parameters for controlling the amount of space within containing
> parentheses, braces, and square brackets. The example below shows the effect
> of the three possible values, 0, 1, and 2, for the case of parentheses:
>
>  if ( ( my $len_tab = length( $tabstr ) ) > 0 ) {  # -pt=0
>  if ( ( my $len_tab = length($tabstr) ) > 0 ) {    # -pt=1 (default)
>  if ((my $len_tab = length($tabstr)) > 0) {        # -pt=2
> A value of 0 causes all parens to be padded on the inside with a space, and
> a value of 2 causes this never to happen. With a value of 1, spaces will be
> introduced if the item within is more than a single token.
.perltidyrc has explicit settings for tight braces and square brackets so …
> Don't enforce tight parens with perltidy

- plugins/karma_tool
- plugins/tls_cert
In light of [gethostbyname being unsafe on Linux](http://www.openwall.com/lists/oss-security/2015/01/27/9), this PR replaces a couple shell command DNS lookups with perl based ones.
Note:  [Sys::Hostname](http://perldoc.perl.org/Sys/Hostname.html) appears to be safe, as it calls gethostname(), which is different than the exploitable gethostbyname().
> use perl DNS methods instead of shell cmds

- .perltidyrc
> Likewise, the parameter -sbt=n or --square-bracket-tightness=n controls the
> space within square brackets, as illustrated below.
>
>  $width = $col[ $j + $k ] - $col[ $j ];  # -sbt=0
>  $width = $col[ $j + $k ] - $col[$j];    # -sbt=1 (default)
>  $width = $col[$j + $k] - $col[$j];      # -sbt=2
> Curly braces which do not contain code blocks are controlled by the
> parameter -bt=n or --brace-tightness=n.
>
>  $obj->{ $parsed_sql->{ 'table' }[0] };    # -bt=0
>  $obj->{ $parsed_sql->{'table'}[0] };      # -bt=1 (default)
>  $obj->{$parsed_sql->{'table'}[0]};        # -bt=2
As with PR #201, I can't find any previous concensus on introducing this
and for myself, I prefer the default.
FTR I can't find anything else in .perltidyrc that I have any bones with :)
> No tight square brackets or curly braces

- lib/Qpsmtpd/TcpServer.pm
- lib/Qpsmtpd/TcpServer/Prefork.pm
- plugins/dmarc
- plugins/tls
- plugins/tls_cert
- qpsmtpd-forkserver
- qpsmtpd-prefork
* update tcpenv and lrpip calls to use -> syntax
* don't load plugins twice.
Not exactly sure where that feature crept in some time ago. It was suppressed by checking to see if a queue plugin was already registered, and then bailing out on subsequent register_hook runs. I noticed it in testing, b/c I didn't have a queue plugin loaded. This removes the duplicate calls to register_hook.
* other PBP changes (early exits, less indention, fewer unnecessary parens,
etc.)
> update tcpenv and lrpip calls to use -> syntax

- plugins/tls
- plugins/tls_cert
> Even if you are offering Perfect Forward Secrecy, very few clients will take advantages. - Ladar Levison, Lavabit
That's no longer true, after the shutdown of Lavabit and the revelation from Edward Snowden. Today, more and more applications start supporting DHE based encryption to enable Perfect Forward Secrecy. The massive government surveillance told us a lesson, even using SSL/TLS and AES is not enough. If you lost your private key, captured traffic from any time period, can be easily decrypted.
It is worthy to support such important feature in the `tls` module. This patch allows `tls` accepts a parameter, `dhparam_path`, and allows `tls_cert` to generate `dhparam` file. But there are some issues to solve, that's why this is a RFC:
1. Does the connection work without issue if …
> [RFC] tls: adding support of Perfect Forward Secrecy

- lib/Qpsmtpd/SMTP.pm
(for cases where the field had more than one = sign)
> limit split = to 2 fields

- t/qpsmtpd.t
This makes the test more universally useful in exercising run_continuation()
itself even with forks that e.g. use custom greetings
> Use a fake greeting for testing run_continuation()

- plugins/ident/geoip
aka: Revert "Revert "Don't crash QP when GeoIP data is missing""
further down the looking glass
Reverts smtpd/qpsmtpd#237
> Don't crash QP when GeoIP data is missing

- plugins/helo
The helo plugin is supposed to reject if HELO is localhost but the email is not coming from localhost.
The last patch broke this and will reject everything unless IP is localhost or HELO is localhost.
> Should only reject if host is not localhost but HELO claims to be one

- plugins/helo
- t/plugin_tests/helo
This corrects an issue raised by Chris Dallimore on the email list.
````
To: qpsmtpd@perl.org
From: Chris Dallimore <snip>
Subject: helo plugin fails to match badhelo
The helo plugin fails to match any entries in badhelo, as the is_regex_match sub returns after the first (usually unsuccessful) test.
This works for me:
--- a/plugins/helo
+++ b/plugins/helo
@@ -301,40 +301,27 @@
sub is_in_badhelo {
my ($self, $host) = @_;
-
-    my $error = "I do not believe you are $host.";
+    my $error = "Your HELO hostname is not allowed";
$host = lc $host;
foreach my $bad ($self->qp->config('badhelo')) {
if ($bad =~ /[\{\}\[\]\(\)\^\$\|\*\+\?\\\!]/) {    # it's a regexp
-            return $self->is_regex_match($host, $bad);
+            #$self->log( LOGDEBUG, "is regex ($bad)");
+            if …
```
> check *every* regex, not just first

- plugins/spamassassin
The hack for outlook (replacing CR in X-Spam-Status header) assumes
that there is only a single occurance of CR. However, if spamassassin
adds some more spam status information X-Spam-Status might be several lines
long leading to multiple occurance of CR.
This fix changes the substitute to a global subsititute, replacing all
CRs in the X-SPam-Status header.
> Replace all occurances of CR in X-Spam-Status

- plugins/spamassassin
Allow setting the size limit to handle by the plugin, instead of the hardcoded 500_000 value
> New size_limit param for spamassassin plugin

- plugins/tls
Some users might need to enable the old SSLv3, or others might want to disable TLSv1. Lets make this configurable.
The default value is kept, but can be overriden in the tls_protocols config file
> Allow setting TLS protocol versions in a config file

- plugins/uribl
When hooking into data, there's no email body to check, so no URI is found
> uribl needs to hook in data_post

- plugins/helo
In the helo plugin. Full warn is:
Use of implicit split to @_ is deprecated at /usr/share/qpsmtpd/plugins/helo line 524
> Prevent a "Use of implicit split" warning

- lib/Qpsmtpd/TcpServer.pm
This patch prevent credentials being logged when using PLAIN AUTH (without, we can see a base64 encoded concatenation of the login and the password in the log). If you set the highest log level, you'll still get them if needed, but not when running in production (using a lower log level)
> Prevent credentials being logged in plain text

- plugins/karma
The default behaviour (connection needs to have at least 3 or -3 to be considered
nice or naughty) is not always what we want, depending on the number of plugins
which adjust the karma. Lets make it configurable
> Possibility to set the number of "strikes" for the karma plugin

- config.sample/karma_tlds
- plugins/karma
The hardcoded list of spammy tlds can't fit every needs. Makes this configurable through a config file.
You can now also raise the karma for tlds you want.
The default config provided keep the same behaviour as before.
> Make spammy_tlds configurable

- lib/Qpsmtpd/Plugin.pm
When using the naughty plugin to defer rejection, we loose the name of the original plugin which caused the reject.
Especially when we parse the logterse plugin output to build graphs. With this addition, we can now get this information back. Eg, before:
2016-04-21 15:02:29.006734500 26288 (deny) logging::logterse: ` 1.2.3.4   mx.bad.biz   mx.bad.biz       <fws@bad.biz> <dani@home.org>        naughty 903     very bad karma: -7 msg denied before queued
After:
2016-04-21 15:02:29.006734500 26288 (deny) logging::logterse: ` 1.2.3.4   mx.bad.biz   mx.bad.biz       <fws@bad.biz> <dani@home.org>        naughty 903     (karma) very bad karma: -7 msg denied before queued
> Record the name of the original plugin

- plugins/dmarc
Because $pol->rua returns undef is there's no rua defined, an error is printed in the logs
FATAL PLUGIN ERROR [dmarc]:  URI string is required! at /usr/share/perl5/vendor_perl/Mail/DMARC/PurePerl.pm line 295
> Check rua is defined before trying to parse it

- docs/hooks.md
- plugins/dmarc
Clearly explain that data_post_headers is only to alter headers, and no reject can be done. Also add a hook in data_post for the dmarc plugin, to do the real reject.
Fix #258
> Update data_post_headers doc

- docs/hooks.md
- plugins/dmarc
Add the dmarc_reject note in the transaction instead of the connection. Even if uncommon, it's probably possible to have one invalid and one valid email in a single connection
> Fix dmarc reject

- plugins/karma
Commit 5e157d2 introduced this bug: for negative karma, we have to check against negative strikes
> Check for negative strikes in karma

- lib/Qpsmtpd.pm
Prevent the following error if we receive an invalid RCPT TO (eg <"relaytest%nmap.scanme.org">)
Can't call method "qp" on an undefined value at /usr/share/perl5/vendor_perl/Qpsmtpd.pm line 451.
/usr/bin/qpsmtpd-forkserver[17472]: command 'rcpt' failed unexpectedly
> Check $addr is defined before using it

- plugins/dkim
To prevent a fatal plugin error in case of DNS timeout
> Use eval to get dkim policies

- plugins/logging/file
I still get a
FATAL PLUGIN ERROR [logging::file_3a7]: Can't call method "notes" on unblessed reference at /home/smtpd/qpsmtpd/plugins/logging/file line 279.
message from the current HEAD. This patch fixes it.
> Fix Can't call method 'notes' on unblessed reference in plugins/logging/file.

- plugins/badmailfromto
- plugins/logging/file
This is just a nit, but I got bitten by the fact that the badmailfromto configuration file allows only one tab (other than the other badmailxxx files).
> Badmailfromto whitespace

- plugins/tls
In d5954ce249646f20151d40a4aaee0eafdca255af, dhparam has been added
to the tls plugin. But a typo was made, misspelled "sp" as "self".
This commit corrects this typo.
Signed-off-by: Tom Li <biergaizi@member.fsf.org>
> tls: fix a typo in SSL_dh_file.

- packaging/rpm/qpsmtpd.spec.in
This series of commits fixes the rpm qpec file so it builds cleanly with the current master branch (d00a82d)
> Fix rpm packaging

- plugins/spamassassin
This change implements so if the 'reject' argument is set to the string 'userprefs' instead of a decimal value, the required threashold value will be taken from spamassassin userprefs required_score instead of set to a static value. This allows a per-user based threshold value.
> Support for spamassassin userprefs - reject threshold

- plugins/ident/geoip
Makes plugin try the more accurate GeoIP v2 before v1 (fallback).
Fixes #289
> Change GeoIP order

- lib/Qpsmtpd/Auth.pm
Based on the idea and patch linked from here: https://www.linkedin.com/pulse/howto-add-fail2ban-support-qpsmtpd-authentication-failures-andrew-pam/
Basically, just add the IP address to the log for other tools (in my case fail2ban) to parse and ban IPs that fail to authenticate.
This is ever so slightly different, as the link above is 5 years old. I tried this out directly against 0.94-4 in Debian Buster, then replicated the one-line change against current master.
> Adding IP address to logs for 535 LOGIN errors, to use with fail2ban

- plugins/tls
To make it easier to use Letsencrypt certificates with the tls plugin, I'd just like to propose to change the file test operators to `-r` as proposed in [this comment](https://community.letsencrypt.org/t/how-do-i-use-lets-encrypt-certs-in-qpsmtpd/142370/4).
> Use readable file test for certificate files

- plugins/whitelist
As ist seems, I had forgotten to add the use statement from #287 when adding the ip-range whitelist feature in 2021. 
This should be fixed now.
The error message was:
FATAL PLUGIN ERROR [whitelist]:  Can't locate object method "new" via package "NetAddr::IP" (perhaps you forgot to load "NetAddr::IP"?) at /usr/share/qpsmtpd/plugins/whitelist line 148.
> Add missing use statement for NetAddr::IP to whitelist plugin

- lib/Qpsmtpd/SMTP.pm
As specified in issue #309 there was a bug when using the received_line hook.
When the received_line hook returned a result, the calling method returned the new line instead of adding it to the header (see Debian bug #933679)
Closes #309
> Fix received_line hook behaviour

- qpsmtpd-forkserver
Removes the comment from line 196, which enables the loading of plugins at startup again. Otherwise there would have been the need for a SIGHUP in order to load the plugins initially.
Closes #308 and #288.
> Load plugins in qpsmtpd-forkserver at startup again

- lib/Qpsmtpd/Postfix.pm
When the postfix queue plugin was added in 5abf363 (Added Postfix queue plugin thanks to Peter J Holzer!, 2004-02-19), some leftover debugging seems to have been included.
The 'print STDERR "hdr: $_\n";' line causes the full headers of every message to be logged.  A few lines below, a similar statement for the body lines is commented out.  Do the same for the header statement.
> postfix: avoid logging full headers

- docs/config.md
- lib/Qpsmtpd/SMTP.pm
When using a cluster of servers, it's sometimes needed to have the same ID in the Authentication-Results header, rather than just the hostname, and you don't always want to change "me" (because that has other effects).  Allow an alternate "ar-me" config file.
> Allow an alternate ID for Authentication-Results
